language: python
python:
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
- pip install pyflakes
- pip install coveralls
before_script:
- make pyflakes
script:
- env
- make test-travis-ci
- make coverage
after_success: coveralls
