language: python
python:
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
- pip install pyflakes
- pip install coveralls
before_script:
- make pyflakes
script:
- make test
- make coverage
after_success: coveralls
env:
  global:
    secure: Rqe3wVJq8InD8C1H0zBWzqA53Uzrv0M99S7VjtAyzkwnSLhUgnrjGJuLTt1h+t3bL6NGmOPpbB4KUWSnH4VDEQCkDmWj5JsPBK0XwIdX33UPiSzhDwscog/Wl14+gX0j3bbi7SY+3Vxf5r7OZ/RJxQZm4n3DJM6qTTqukemF3iKp9Hg70kK3G2V/Of969IOklri2UN8cMq+gxoyghuZVhC5PYZ+zgC8aq86Cd7OE6PPQA7pT6ym+HH1grVAhpq7azwfkMItLuKM8GzXQIvA+wl681cZ9tGGYknFCvR+cGUjTHE1SsvadFMKSkkosZk4s31OcOqmJYDjo2RFoUJOkfMgzBEDscT/koEOiSYuDSxedg+AsARe8C24EJWEHzHHTyrqRLNlpBZ3FTJcZ+1JhYjYMDi8Nsrr6APLw9Hd6yUu4uCQT9m8zTUyG8ZrnAG+wo1yQD8KsM/TMnBLbXYa/2uQT5Av723gtQieMeZbmiUldnvBoZ6r9ou+hVhCuecy0tUpgvnJV8LdCO/GgHJWeoH11LZVZVFMJ+UKaZuzxOrGyifxyraerHHwfiF9gWquywTbx4sYRHUWR+V6IuWb0hAht/ZWzbrCOim4EhJBmrPEQUZx0SyTxz9+LNQ+KRoXHgDIzNfLB3HVuEdpRyboo6ZWHgmlwOIQCLzTpF+eoJ2c=
